// ============================================================
// Domnotate — MAIN world content script
// ============================================================
//
// Runs in the page's own JS realm, so it can reach framework internals
// (`__reactFiber$*`, `__vueParentComponent`, `__svelte_meta`, …) that the
// ISOLATED world cannot see. It touches nothing else: it answers nonce-tagged
// requests with a serializable hint and does not modify the page.
//
// The describer contract, which any provider added here must honour:
//   • pure function of `(element) -> SourceHint | null`
//   • output is structured-clone safe: no functions, no DOM nodes, no cycles,
//     no raw `__reactProps$*` dumps (§3.7 allow-list floor)
//   • never throws — a describer failure degrades to `null`, it does not break
//     the pick (the catch below enforces this, but do not rely on it)
//
// Tier C (React fibers, §3.6) registers here: this is the only script with a
// view of the page's own JS realm.

import { createDomProvider } from '@/core/source-hint/dom-provider';
import { createProviderRegistry } from '@/core/source-hint/provider';
import {
  HINT_CHANNEL,
  HINT_TARGET_ATTR,
  isHintRequest,
  type HintResponseMessage,
  type SourceHintPayload,
} from '@/extension/hint-protocol';

export type HintDescriber = (el: Element) => SourceHintPayload | null;

/** Nonces are generated by `createNonce()`; nothing else is honoured. */
const SAFE_NONCE = /^[A-Za-z0-9-]+$/;

/**
 * Empty-but-valid hint. Retained as the degradation target: a describer that
 * throws, or a page with no active provider, still answers with this shape
 * rather than breaking the pick.
 */
export const describeStub: HintDescriber = () => ({
  signals: [],
  confidence: 'weak',
  provider: 'none',
});

/**
 * The Tier A/B floor (§3.6): pure DOM, no framework cooperation, so it runs on
 * any site. Built once per injection — the registry is stateless per call.
 */
function createDefaultDescriber(win: Window): HintDescriber {
  const registry = createProviderRegistry([createDomProvider({ window: win })]);
  return (el) => registry.describe(el);
}

export interface SourceHintResponderOptions {
  win?: Window;
  describe?: HintDescriber;
}

/**
 * Listen for hint requests and answer them. Returns an uninstall function.
 * Safe to call more than once; each call installs an independent listener, so
 * the injection guard lives in the caller.
 */
export function installSourceHintResponder(
  options: SourceHintResponderOptions = {},
): () => void {
  const win = options.win ?? window;
  const describe = options.describe ?? createDefaultDescriber(win);

  const onMessage = (event: MessageEvent): void => {
    const data: unknown = event.data;
    if (!isHintRequest(data)) return;
    // Anything on the page can post to this window, so the nonce is
    // interpolated into a selector only after it is proven inert.
    if (!SAFE_NONCE.test(data.nonce)) return;

    const el = win.document.querySelector(`[${HINT_TARGET_ATTR}="${data.nonce}"]`);

    let hint: SourceHintPayload | null = null;
    if (el) {
      // Untag before describing, or the nonce lands in the element's own
      // attributes and we export our own plumbing. The ISOLATED world removes
      // it again when the response arrives; removing twice is harmless.
      el.removeAttribute(HINT_TARGET_ATTR);
      try {
        hint = describe(el);
      } catch {
        // A broken describer degrades to "no hint", never to a broken pick.
        hint = null;
      }
    }

    const response: HintResponseMessage = {
      channel: HINT_CHANNEL,
      kind: 'response',
      nonce: data.nonce,
      hint,
    };
    const origin = win.location?.origin;
    win.postMessage(response, !origin || origin === 'null' ? '*' : origin);
  };

  win.addEventListener('message', onMessage);
  return () => win.removeEventListener('message', onMessage);
}

/**
 * Where the resident copy parks its uninstall function, so a later injection
 * can take over from it.
 */
const UNINSTALL_KEY = '__domnotateMainUninstall';

/**
 * Entry point. Re-injection must not stack listeners, but it must not *skip*
 * either: this script lives in the page's realm and survives everything short
 * of a page load, so a copy injected before the extension was rebuilt is still
 * resident and still answering. Skipping left it in charge, and hints kept
 * coming back from the old describer while the ISOLATED world — which
 * remounts per activation — was already running new code.
 *
 * So: replace rather than skip. Exactly one responder, always the newest.
 */
export function bootstrapMainWorld(win: Window = window): boolean {
  const scope = win as unknown as Record<string, unknown>;
  const previous = scope[UNINSTALL_KEY];
  const replaced = typeof previous === 'function';
  if (replaced) (previous as () => void)();

  scope[UNINSTALL_KEY] = installSourceHintResponder({ win });
  return !replaced;
}

/** Remove the resident responder, if any. Returns whether one was there. */
export function teardownMainWorld(win: Window = window): boolean {
  const scope = win as unknown as Record<string, unknown>;
  const uninstall = scope[UNINSTALL_KEY];
  if (typeof uninstall !== 'function') return false;
  (uninstall as () => void)();
  delete scope[UNINSTALL_KEY];
  return true;
}

// Auto-run when injected as a content script. Skipped under the unit-test DOM
// so the module can be imported and exercised with an explicit window.
if (import.meta.env.MODE !== 'test') {
  bootstrapMainWorld();
}
