import { describe, test, expect } from 'vitest';

import { createEventBus } from '@/events';
import { createAnnotationManager } from '@/annotations/annotation-manager';
import { createTextEditor } from '@/editor/edit-mode';
import { createEditManager } from '@/editor/edit-manager';
import { editTargetKey } from '@/editor/edit-identity';
import { createOutputFormatter } from '@/output/formatter';
import { snapshotAnnotationPreviews } from '@/output/annotation-preview';
import { serializeSession, deserializeSession, validateSession } from '@/output/json-io';
import { reanchorAnnotation } from '@/output/reanchor';
import { generateDescriptor, generateCssSelector, generateXPath } from '@/picker/selector-engine';
import { createNotePopover } from '@/popover/popover';
import { createToast } from '@/toast/toast';
import { attachTooltip } from '@/tooltip/tooltip';
import { createSlideObserver } from '@/slides/slide-observer';
import { activateScopeRecord, ACTIVATION_STRATEGIES } from '@/slides/activation-strategy';
import { createKeyboardShortcuts } from '@/keyboard/shortcuts';
import { createContentLoader } from '@/loader/loader';
import { fetchShare, publishShare, republishAnnotations, republishSession } from '@/share/share-client';
import { sessionFromSharedBlob } from '@/share/hydration';
import { createSharedSessionBlob } from '@/share/shared-session';
import {
  describePinVisibility,
  generateScopeDiagnostics,
  isElementSuspiciouslyUnscoped,
} from '@/diagnostics/scope-diagnostics';
import { scopeAnnotationToCurrentPanel } from '@/diagnostics/scope-override';
import { isDiagnosticsEnabled, mountDiagnosticsPanel } from '@/diagnostics/diagnostics-panel';
import { createPageHost, createIframeHost } from '@/core/content-host';
import { isHashClass } from '@/core/class-hash';
import { createProviderRegistry, mergeSignals, filterProps } from '@/core/source-hint/provider';
import { createDomProvider } from '@/core/source-hint/dom-provider';
import { formatSourceHint } from '@/core/source-hint/format';
import { requestSourceHint } from '@/extension/hint-protocol';
import { installSourceHintResponder } from '@/extension/content-main';
import { mountDomnotate } from '@/extension/content-isolated';
import { installExtensionShortcuts } from '@/extension/shortcuts';
import { registerCommandHandler, TOGGLE_COMMAND } from '@/extension/background';
import { runCopyFeedback, flyPinsToButton, popIcon } from '@/sidebar/copy-animation';
import { createChangelog } from '@/changelog/changelog';
import { CHANGELOG } from '@/changelog/changelog-data';

describe('smoke: core module exports', () => {
  test('all core modules export expected functions', () => {
    expect(typeof createEventBus).toBe('function');
    expect(typeof createAnnotationManager).toBe('function');
    expect(typeof createTextEditor).toBe('function');
    expect(typeof createEditManager).toBe('function');
    expect(typeof editTargetKey).toBe('function');
    expect(typeof createOutputFormatter).toBe('function');
    expect(typeof snapshotAnnotationPreviews).toBe('function');
    expect(typeof serializeSession).toBe('function');
    expect(typeof deserializeSession).toBe('function');
    expect(typeof validateSession).toBe('function');
    expect(typeof reanchorAnnotation).toBe('function');
    expect(typeof generateDescriptor).toBe('function');
    expect(typeof generateCssSelector).toBe('function');
    expect(typeof generateXPath).toBe('function');
    expect(typeof createNotePopover).toBe('function');
    expect(typeof createToast).toBe('function');
    expect(typeof attachTooltip).toBe('function');
    expect(typeof createSlideObserver).toBe('function');
    expect(typeof activateScopeRecord).toBe('function');
    expect(Array.isArray(ACTIVATION_STRATEGIES)).toBe(true);
    expect(typeof createKeyboardShortcuts).toBe('function');
    expect(typeof createContentLoader).toBe('function');
    expect(typeof publishShare).toBe('function');
    expect(typeof fetchShare).toBe('function');
    expect(typeof republishAnnotations).toBe('function');
    expect(typeof republishSession).toBe('function');
    expect(typeof sessionFromSharedBlob).toBe('function');
    expect(typeof createSharedSessionBlob).toBe('function');
    expect(typeof generateScopeDiagnostics).toBe('function');
    expect(typeof describePinVisibility).toBe('function');
    expect(typeof isElementSuspiciouslyUnscoped).toBe('function');
    expect(typeof scopeAnnotationToCurrentPanel).toBe('function');
    expect(typeof isDiagnosticsEnabled).toBe('function');
    expect(typeof mountDiagnosticsPanel).toBe('function');
    expect(typeof createPageHost).toBe('function');
    expect(typeof isHashClass).toBe('function');
    expect(typeof createIframeHost).toBe('function');
    expect(typeof createProviderRegistry).toBe('function');
    expect(typeof mergeSignals).toBe('function');
    expect(typeof filterProps).toBe('function');
    expect(typeof createDomProvider).toBe('function');
    expect(typeof formatSourceHint).toBe('function');
    expect(typeof requestSourceHint).toBe('function');
    expect(typeof installSourceHintResponder).toBe('function');
    expect(typeof mountDomnotate).toBe('function');
    expect(typeof installExtensionShortcuts).toBe('function');
    expect(typeof registerCommandHandler).toBe('function');
    expect(typeof TOGGLE_COMMAND).toBe('string');
    expect(typeof runCopyFeedback).toBe('function');
    expect(typeof flyPinsToButton).toBe('function');
    expect(typeof popIcon).toBe('function');
    expect(typeof createChangelog).toBe('function');
    expect(Array.isArray(CHANGELOG)).toBe(true);
  });
});
