// ============================================================
// Domnotate — the mark
// ============================================================
//
// GENERATED by `npm run mark` (tools/make-mark.mjs). Do not edit.
//
// The full variant. The app never renders the mark small enough to need the
// 16px one.

const SVG_NS = 'http://www.w3.org/2000/svg';

/** One shape of the mark: an element name and its attributes. */
type MarkShape = readonly [string, Readonly<Record<string, string | number>>];

/** The mark, bleeding to a 128-unit square. */
export const MARK_SHAPES: readonly MarkShape[] = [
  ['rect', {"x":0,"y":0,"width":128,"height":128,"rx":32,"fill":"#C4725A"}],
  ['line', {"x1":18.56,"y1":12.8,"x2":109.44,"y2":12.8,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":25.6,"x2":109.44,"y2":25.6,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":38.4,"x2":63.49,"y2":38.4,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":94.05,"y1":38.4,"x2":109.44,"y2":38.4,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":51.2,"x2":64.59,"y2":51.2,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":90.51,"y1":51.2,"x2":109.44,"y2":51.2,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":64,"x2":56.38,"y2":64,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":70.8,"y1":64,"x2":109.44,"y2":64,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":76.8,"x2":48.17,"y2":76.8,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":61.94,"y1":76.8,"x2":109.44,"y2":76.8,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":89.6,"x2":41.45,"y2":89.6,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":51.6,"y1":89.6,"x2":109.44,"y2":89.6,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":102.4,"x2":109.44,"y2":102.4,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['line', {"x1":18.56,"y1":115.2,"x2":109.44,"y2":115.2,"stroke":"#FAF7F2","stroke-opacity":0.14,"stroke-width":2.34,"stroke-linecap":"round"}],
  ['path', {"d":"M 38.16 102.16 L 55.69 81.84 L 50.16 78.16 L 38.16 102.16 Z","fill":"#FAF7F2"}],
  ['circle', {"cx":52.93,"cy":80,"r":3.32,"fill":"#FAF7F2"}],
  ['path', {"d":"M 55.69 81.84 L 75.89 52.64 L 69.34 48.27 L 50.16 78.16 Z","fill":"#FAF7F2"}],
  ['circle', {"cx":72.61,"cy":50.46,"r":3.94,"fill":"#FAF7F2"}],
  ['circle', {"cx":78.77,"cy":41.84,"r":12.93,"fill":"#2C2016"}],
];

/**
 * Build the mark as an `<svg>` element `size` px square. The panel bleeds to the
 * box, so `size` is what the mark actually paints.
 *
 * Built element by element, not from a markup string: the extension certifies to
 * the Chrome Web Store that it assigns no innerHTML, and it shares this module.
 */
export function createMarkElement(size: number, doc: Document = document): SVGSVGElement {
  const svg = doc.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('viewBox', '0 0 128 128');
  svg.setAttribute('width', String(size));
  svg.setAttribute('height', String(size));
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');

  for (const [tag, attrs] of MARK_SHAPES) {
    const node = doc.createElementNS(SVG_NS, tag);
    for (const [name, value] of Object.entries(attrs)) {
      node.setAttribute(name, String(value));
    }
    svg.appendChild(node);
  }

  return svg;
}
